version: '3.4'
services:
  app:
    image: alexhorn/watchpoint:latest
    restart: always
    network_mode: host
    volumes:
      - "/etc/watchpoint:/etc/watchpoint"
      - "/var/lib/watchpoint:/var/lib/watchpoint"
    environment:
      - WATCHPOINT_PORT=80
  watchtower:
    image: containrrr/watchtower
    restart: always
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
