version: '3.4'
services:
  app:
    image: watchpoint:latest
    restart: always
    network_mode: host
    volumes:
      - "/etc/watchpoint:/etc/watchpoint"
      - "/var/lib/watchpoint:/var/lib/watchpoint"
    environment:
      - WATCHPOINT_PORT=80
